### ISSUE TITLE
how to get 'data/POS-penn/wsj/split1/wsj1.train.original'

### ISSUE THREAD

**Issue by SeekPoint** [XuezheMax/NeuroNLP2#26]
mldl@ub1604:~/ub16_prj/NeuroNLP2$ bash examples/run_posCRFTagger.sh 
embedding_path is  data/glove/glove.6B/glove.6B.100d.gz
loading embedding: glove from data/glove/glove.6B/glove.6B.100d.gz
2018-08-29 17:03:57,003 - POSCRFTagger - INFO - Creating Alphabets
2018-08-29 17:03:57,003 - Create Alphabets - INFO - Creating Alphabets: data/alphabets/pos_crf/
Traceback (most recent call last):
  File "examples/posCRFTagger.py", line 220, in <module>
    main()
  File "examples/posCRFTagger.py", line 82, in main
    max_vocabulary_size=50000, embedd_dict=embedd_dict)
  File "./neuronlp2/io/conllx_data.py", line 88, in create_alphabets
    with open(train_path, 'r') as file:
IOError: [Errno 2] No such file or directory: 'data/POS-penn/wsj/split1/wsj1.train.original'

**Comment by XuezheMax** [comment]
The data are from Penn Treebank (PTB).

**Comment by SeekPoint** [comment]
can you provide it, thanks

**Comment by XuezheMax** [comment]
The data is under licence and please make sure that it is not an issue for you.
Please send me your email so that I can share you the data.

**Comment by SeekPoint** [comment]
I sent email to you , please check it

**Comment by XuezheMax** [comment]
I have sent you the data, you haven’t received it?

**Comment by SeekPoint** [comment]
Get it , thanks
