### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded  (python3+torch0.4)

### ISSUE THREAD

**Issue by SeekPoint** [XuezheMax/NeuroNLP2#27]
mldl@ub1604:~/ub16_prj/NeuroNLP2$ bash examples/run_posCRFTagger.sh
embedding_path is  data/glove/glove.6B/glove.6B.100d.gz
loading embedding: glove from data/glove/glove.6B/glove.6B.100d.gz
2018-09-03 09:43:35,189 - POSCRFTagger - INFO - Creating Alphabets
2018-09-03 09:43:35,190 - Create Alphabets - INFO - Creating Alphabets: data/alphabets/pos_crf/
2018-09-03 09:43:38,950 - Create Alphabets - INFO - Total Vocabulary Size: 38406
2018-09-03 09:43:38,950 - Create Alphabets - INFO - Total Singleton Size:  16938
2018-09-03 09:43:38,973 - Create Alphabets - INFO - Total Vocabulary Size (w.o rare words): 35154
2018-09-03 09:43:40,167 - Create Alphabets - INFO - Word Alphabet Size (Singleton): 39266 (13686)
2018-09-03 09:43:40,167 - Create Alphabets - INFO - Character Alphabet Size: 88
2018-09-03 09:43:40,167 - Create Alphabets - INFO - POS Alphabet Size: 48
2018-09-03 09:43:40,167 - Create Alphabets - INFO - Type Alphabet Size: 15
2018-09-03 09:43:40,169 - POSCRFTagger - INFO - Word Alphabet Size: 39266
2018-09-03 09:43:40,169 - POSCRFTagger - INFO - Character Alphabet Size: 88
2018-09-03 09:43:40,169 - POSCRFTagger - INFO - POS Alphabet Size: 48
2018-09-03 09:43:40,169 - POSCRFTagger - INFO - Reading Data
reading data: 10000
reading data: 20000
reading data: 30000
Total number of data: 38218
Reading data from data/POS-penn/wsj/split1/wsj1.dev.original
Total number of data: 5527
./neuronlp2/io/conllx_data.py:371: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  words = Variable(torch.from_numpy(wid_inputs), volatile=volatile)
./neuronlp2/io/conllx_data.py:372: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  chars = Variable(torch.from_numpy(cid_inputs), volatile=volatile)
./neuronlp2/io/conllx_data.py:373: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  pos = Variable(torch.from_numpy(pid_inputs), volatile=volatile)
./neuronlp2/io/conllx_data.py:374: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  heads = Variable(torch.from_numpy(hid_inputs), volatile=volatile)
./neuronlp2/io/conllx_data.py:375: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  types = Variable(torch.from_numpy(tid_inputs), volatile=volatile)
./neuronlp2/io/conllx_data.py:376: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  masks = Variable(torch.from_numpy(masks), volatile=volatile)
./neuronlp2/io/conllx_data.py:377: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  single = Variable(torch.from_numpy(single), volatile=volatile)
Reading data from data/POS-penn/wsj/split1/wsj1.test.original
Total number of data: 5462
oov: 954
2018-09-03 09:43:58,409 - POSCRFTagger - INFO - constructing network...
Traceback (most recent call last):
  File "examples/posCRFTagger.py", line 220, in <module>
    main()
  File "examples/posCRFTagger.py", line 127, in main
    tag_space=tag_space, embedd_word=word_table, bigram=bigram, p_in=p_in, p_out=p_out, p_rnn=p_rnn, initializer=initializer)
  File "./neuronlp2/models/sequence_labeling.py", line 201, in __init__
    p_in=p_in, p_out=p_out, p_rnn=p_rnn, initializer=initializer)
  File "./neuronlp2/models/sequence_labeling.py", line 16, in __init__
    self.word_embedd = Embedding(num_words, word_dim, init_embedding=embedd_word)
  File "./neuronlp2/nn/modules/sparse.py", line 53, in __init__
    self.reset_parameters(init_embedding)
  File "./neuronlp2/nn/modules/sparse.py", line 60, in reset_parameters
    assign_tensor(self.weight, init_embedding)
  File "./neuronlp2/nn/init.py", line 17, in assign_tensor
    assign_tensor(tensor.data, val)
  File "./neuronlp2/nn/init.py", line 17, in assign_tensor
    assign_tensor(tensor.data, val)
  File "./neuronlp2/nn/init.py", line 17, in assign_tensor
    assign_tensor(tensor.data, val)
i

  File "./neuronlp2/nn/init.py", line 16, in assign_tensor
    if isinstance(tensor, Variable):
RuntimeError: maximum recursion depth exceeded
mldl@ub1604:~/ub16_prj/NeuroNLP2$

**Comment by XuezheMax** [comment]
You need to switch to the branch for pytorch0.4

**Comment by SeekPoint** [comment]
it works

**Comment by vedic-partap** [comment]
> You need to switch to the branch for pytorch0.4

I didn't understand. How to do it ?

**Comment by SeekPoint** [comment]
@vedic-partap 

git checkout remotes/origin/pytorch4.0
