### ISSUE TITLE
No such file or directory: 'data/sskip/sskip.ger.64.gz'  && data/sskip/sskip.eng.100.gz && data/conll2003/english/eng.train.bioes.conll

### ISSUE THREAD

**Issue by SeekPoint** [XuezheMax/NeuroNLP2#29]
mldl@ub1604:~/ub16_prj/NeuroNLP2$ bash examples/run_ner_ger.sh 
loading embedding: sskip from data/sskip/sskip.ger.64.gz
Traceback (most recent call last):
  File "examples/NERCRF.py", line 248, in <module>
    main()
  File "examples/NERCRF.py", line 94, in main
    embedd_dict, embedd_dim = utils.load_embedding_dict(embedding, embedding_path)
  File "./neuronlp2/utils.py", line 69, in load_embedding_dict
    with gzip.open(embedding_path, 'r') as file:
  File "/usr/lib/python3.5/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/sskip/sskip.ger.64.gz'
mldl@ub1604:~/ub16_prj/NeuroNLP2$

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/NeuroNLP2$ bash examples/run_graphParser.sh 
loading embedding: sskip from data/sskip/sskip.eng.100.gz
Traceback (most recent call last):
  File "examples/GraphParser.py", line 527, in <module>
    main()
  File "examples/GraphParser.py", line 116, in main
    word_dict, word_dim = utils.load_embedding_dict(word_embedding, word_path)
  File "./neuronlp2/utils.py", line 69, in load_embedding_dict
    with gzip.open(embedding_path, 'r') as file:
  File "/usr/lib/python3.5/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/sskip/sskip.eng.100.gz'
mldl@ub1604:~/ub16_prj/NeuroNLP2$

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/NeuroNLP2$ bash examples/run_ner.sh 
loading embedding: glove from data/glove/glove.6B/glove.6B.100d.gz
2018-09-03 10:16:41,629 - NER - INFO - Creating Alphabets
2018-09-03 10:16:41,629 - Create Alphabets - INFO - Creating Alphabets: data/alphabets/ner/
Traceback (most recent call last):
  File "examples/NER.py", line 248, in <module>
    main()
  File "examples/NER.py", line 97, in main
    embedd_dict=embedd_dict, max_vocabulary_size=50000)
  File "./neuronlp2/io/conll03_data.py", line 75, in create_alphabets
    with open(train_path, 'r') as file:
IOError: [Errno 2] No such file or directory: 'data/conll2003/english/eng.train.bioes.conll'
mldl@ub1604:~/ub16_prj/NeuroNLP2$

**Comment by XuezheMax** [comment]
for the embedding of structured skip gram, please contact the authors to ask for the embedding files.
For ner data with bioes tagging scheme, you can use the code in #9 to convert the original NER data into the desired format.
