### ISSUE TITLE
whart is /run_analyze.sh used for, looks missing some files

### ISSUE THREAD

**Issue by SeekPoint** [XuezheMax/NeuroNLP2#30]
mldl@ub1604:~/ub16_prj/NeuroNLP2$ bash examples/run_analyze.sh
2018-09-04 12:37:51,549 - Analyzer - INFO - punctuations(5): , : '' . ``
Traceback (most recent call last):
  File "examples/analyze.py", line 480, in <module>
    main()
  File "examples/analyze.py", line 61, in main
    stackptr(model_path, model_name, test_path, punct_set, device, logger, args)
  File "examples/analyze.py", line 193, in stackptr
    type_alphabet = conllx_stacked_data.create_alphabets(alphabet_path, None, data_paths=[None, None], max_vocabulary_size=50000, embedd_dict=None)
  File "./neuronlp2/io/conllx_data.py", line 140, in create_alphabets
    word_alphabet.load(alphabet_directory)
  File "./neuronlp2/io/alphabet.py", line 138, in load
    self.__from_json(json.load(open(os.path.join(input_directory, loading_name + ".json"))))
FileNotFoundError: [Errno 2] No such file or directory: 'models/parsing/stack_ptr/alphabets/word.json'
mldl@ub1604:~/ub16_prj/NeuroNLP2$

**Comment by XuezheMax** [comment]
It is used for evaluating pre-trained models, reporting some statistics for analysis.
